### ISSUE TITLE
Getting error in loading shared libraries

### ISSUE THREAD

**Issue by razapk** [daisukekobayashi/darknet-docker#8]
Hi,
I am getting the following error:
```
darknet: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory
```
My Dockerfile looks like:
```
FROM daisukekobayashi/darknet:gpu-cv-cc86
# I think the lines here are not relevant to the problem
...
darknet detect cfg/yolov3.cfg yolov3.weights data/dog.jpg
```

Thanks in advance,
Raza

**Comment by maininformer** [comment]
@razapk 
try: 
```bash
export LD_LIBRARY_PATH="/usr/local/cuda/compat:${LD_LIBRARY_PATH}"
```
inside the container

Alternatively, you may add the following line to the runtime container; put it in the end
```
 ENV LD_LIBRARY_PATH="/usr/local/cuda/compat:${LD_LIBRARY_PATH}"
```

note you will need to build your own container with this method:
* Copy the `Dockerfile`
* Copy the `configure.sh`
* run `$ chmod +x configure.sh`
* run `$ docker build --build-arg SOURCE_BRANCH=master --build-arg SOURCE_COMMIT=8bbdb --build-arg CONFIG=gpu-cv-cc75 --tag darknet:latest .`

you may replace the `--build-arg`s with your desired values. 

I am hesitant to PR this and will play with it a bit more first.

**Comment by dannje** [comment]
Hello,

I'm getting the same error as above:
`darknet: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory`

After running:
`docker run --runtime=nvidia --rm -v C:\Users\Dan\Desktop\ocv\dockershit\darknet\build\darknet\x64:/workspace -w /workspace daisukekobayashi/darknet:gpu darknet detector test data/coco.data yolov3.cfg yolov3.weights -i 0 -thresh 0.25 dog.jpg -ext_output`

Thanks for your help,
Dan

**Comment by daisukekobayashi** [comment]
@razapk @dannje 
Hi. What OS are you using?
Using ``—runtime=nvidia`` option, you need the [NVIDIA Container Toolkit](https://github.com/NVIDIA/nvidia-docker). And I think that the NVIDIA Container Toolkit only support Linux distributions. You can see supported platforms [here](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#supported-platforms).

In dannje's command, it seems that you are using Windows.

**Comment by razapk** [comment]
@daisukekobayashi 
I am using Ubuntu 20.04.2 LTS and have Nvidia Container Toolkit installed. Here is my docker compose file I am using:
```
version: "3.9"
services:
  backend:
    build: .
    ports:
      - "3333:3333"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu, utility]
```

**Comment by dancronintix** [comment]
I got it working @daisukekobayashi 
Thank you! 

I was on Windows 10 attempting to use WSL which doesn't have CUDA. I needed to install WSL2 and that worked. 👍
